[package]
name = "poseidon-bn254"
version = "0.1.0"
edition = "2021"
authors = ["Morph Developers--changed from Scroll's initial version"]
description = "Poseidon hash implementation for BN254"
license = "MIT OR Apache-2.0"

[dependencies]
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-derive = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-intrinsics = { git = "https://github.com/succinctlabs/sp1.git" }

[dev-dependencies]
itertools = "0.11"

[features]
default = ["std"]
std = []

[[test]]
name = "sp1_tests"
path = "sp1-tests/test-bn254/program/src/main.rs"
required-features = ["std"]

[workspace]
members = [
    "sp1-tests/test-bn254/program",
    "sp1-tests/test-bn254/script",
]

[workspace.dependencies]
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-derive = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-intrinsics = { git = "https://github.com/succinctlabs/sp1.git" }